adminUser:
  password: local:jxrocks/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: zander.hamidi@gmail.com
  token: local:jxrocks/pipelineUser:token
  username: zandabanda
prow:
  hmacToken: local:jxrocks/prow:hmacToken
